"""??

Revision ID: 1d71014d0064
Revises: f030a094fb4f
Create Date: 2021-04-01 21:18:02.675158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d71014d0064'
down_revision = 'f030a094fb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index('ix_history_history_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('ix_history_history_name', ['history_name'], unique=1)

    # ### end Alembic commands ###
