"""add user to l and h

Revision ID: 4695c3408ee1
Revises: b298c9ee2cb8
Create Date: 2021-04-01 14:10:33.712837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4695c3408ee1'
down_revision = 'b298c9ee2cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_history_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_locations_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_locations_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_history_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
