"""user table

Revision ID: 52447bf281f1
Revises: 
Create Date: 2021-03-29 12:05:42.767610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52447bf281f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magickal_interventions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magickal_interventions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
