"""category connections

Revision ID: 96f63c6fef59
Revises: 0a658219e96a
Create Date: 2021-04-07 11:52:07.643524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f63c6fef59'
down_revision = '0a658219e96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sw_id')
        batch_op.drop_column('crops_id')
        batch_op.drop_column('hw_id')

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sw_id')
        batch_op.drop_column('company_id')
        batch_op.drop_column('hw_id')

    with op.batch_alter_table('hw_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sw_id')
        batch_op.drop_column('crops_id')

    with op.batch_alter_table('sw_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('crops_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crops_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'crops', ['crops_id'], ['id'])

    with op.batch_alter_table('hw_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crops_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sw_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'crops', ['crops_id'], ['id'])
        batch_op.create_foreign_key(None, 'sw_products', ['sw_id'], ['id'])

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hw_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sw_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'hw_products', ['hw_id'], ['id'])
        batch_op.create_foreign_key(None, 'sw_products', ['sw_id'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hw_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('crops_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sw_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'hw_products', ['hw_id'], ['id'])
        batch_op.create_foreign_key(None, 'crops', ['crops_id'], ['id'])
        batch_op.create_foreign_key(None, 'sw_products', ['sw_id'], ['id'])

    # ### end Alembic commands ###
