"""revert crops companies

Revision ID: b298c9ee2cb8
Revises: 14d77b5232df
Create Date: 2021-04-01 11:59:43.479533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b298c9ee2cb8'
down_revision = '14d77b5232df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crops_companies_assoc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops_companies_assoc',
    sa.Column('crops_id', sa.INTEGER(), nullable=True),
    sa.Column('companies_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['companies_id'], ['companies.id'], name='fk_crops_companies_assoc_companies_id_companies'),
    sa.ForeignKeyConstraint(['crops_id'], ['crops.id'], name='fk_crops_companies_assoc_crops_id_crops')
    )
    # ### end Alembic commands ###
