"""add user_id to each table

Revision ID: e6bc5c127574
Revises: afaed769139d
Create Date: 2021-03-30 13:27:41.695395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bc5c127574'
down_revision = 'afaed769139d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_companies_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_crops_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('hw_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_hw_products_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('sw_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sw_products_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sw_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sw_products_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('hw_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hw_products_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_crops_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_companies_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
