"""init functions

Revision ID: f030a094fb4f
Revises: f07e6c3e3984
Create Date: 2021-04-01 15:16:47.487076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f030a094fb4f'
down_revision = 'f07e6c3e3984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_locations_location_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_locations_location_name', ['location_name'], unique=1)

    # ### end Alembic commands ###
