"""rename

Revision ID: f07e6c3e3984
Revises: 4695c3408ee1
Create Date: 2021-04-01 14:52:05.451483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07e6c3e3984'
down_revision = '4695c3408ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_table',
    sa.Column('history_id', sa.INTEGER(), nullable=True),
    sa.Column('locations_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], name='fk_history_table_history_id_history'),
    sa.ForeignKeyConstraint(['locations_id'], ['locations.id'], name='fk_history_table_locations_id_locations')
    )
    # ### end Alembic commands ###
